FROM debian:buster

RUN echo 'deb http://archive.debian.org/debian buster main' > /etc/apt/sources.list && \
    echo 'deb http://archive.debian.org/debian-security buster/updates main' >> /etc/apt/sources.list && \
    apt-get update -o Acquire::Check-Valid-Until=false && \
    apt-get install -y --no-install-recommends \
        gcc g++ libc6-dev make pkg-config && \
    rm -rf /var/lib/apt/lists/*
